{
  "swagger": "2.0",
  "host": "localhost:3000",
  "basePath": "/api/v1/",
  "info": {
    "description": "Esta API permite a los usuarios registrar y gestionar clientes y técnicos, así como crear y gestionar solicitudes de servicio.",
    "version": "1.0",
    "title": "API REST SOLITUD DE SERVICIOS",
    "contact": {
      "email": "eliascolon98@gmail.com"
    }
  },
  "tags": [
    {
      "name": "Clientes",
      "description": "Endpoints para Clientes"
    },
    {
      "name": "Tecnicos",
      "description": "Endpoints para Tecnicos"
    },
    {
      "name": "Solicitudes",
      "description": "Endpoints para las solicitudes de servicios"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "paths": {
    "/clientes": {
      "post": {
        "tags": [
          "Clientes"
        ],
        "summary": "Registra un nuevo cliente en la base de datos",
        "description": "Se crea un cliente nuevo y se retorna un json indicado si se guardó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "nombre": {
                  "type": "string",
                  "example": "Elias Colon"
                },
                "direccion": {
                  "type": "string",
                  "example": "Calle 22"
                },
                "correo": {
                  "type": "string",
                  "example": "eliascolon98@gmail.com"
                },
                "phone": {
                  "type": "number",
                  "example": "3185466115"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha realizado correctamente y creado un nuevo cliente.",
            "schema": {
              "$ref": "#/definitions/clienteCreado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      },
      "get": {
        "tags": [
          "Clientes"
        ],
        "summary": "Obtiene una lista de todos los clientes registrados en la base de datos",
        "description": "Este listado obtiene todo los tecnicos en la base de datos.",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "la solicitud se ha realizado correctamente.",
            "schema": {
              "$ref": "#/definitions/crearCliente"
            }
          },
          "400": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          },
          "404": {
            "description": "Pentición no fue encontrada.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    },
    "/clientes/{id}": {
      "get": {
        "tags": [
          "Clientes"
        ],
        "summary": "Obtiene la información de un cliente en particular a partir de su ID",
        "description": "Obtiene cliente especifico según el ID en la base de datos.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "El ID del cliente",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "la solicitud se ha realizado correctamente.",
            "schema": {
              "$ref": "#/definitions/crearCliente"
            }
          },
          "400": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          },
          "404": {
            "description": "Pentición no fue encontrada.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      },
      "put": {
        "tags": [
          "Clientes"
        ],
        "summary": "Actualiza la información de un cliente en particular a partir de su ID",
        "description": "Se actualiza un cliente especifico y se retorna un json indicado si se actualizó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "El ID del cliente",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "nombre": {
                  "type": "string",
                  "example": "Elias Colon"
                },
                "direccion": {
                  "type": "string",
                  "example": "Calle 22"
                },
                "correo": {
                  "type": "string",
                  "example": "eliascolon98@gmail.com"
                },
                "phone": {
                  "type": "number",
                  "example": "3185466115"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha actualizado correctamente el cliente.",
            "schema": {
              "$ref": "#/definitions/clienteActualizado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Clientes"
        ],
        "summary": "Elimina un cliente en particular a partir de su ID",
        "description": "Se elimina un cliente especifico y se retorna un json indicado si se eliminó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "El ID del cliente",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha elminado correctamente el cliente.",
            "schema": {
              "$ref": "#/definitions/clienteEliminado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    },
    
    "/tecnicos": {
      "post": {
        "tags": [
          "Tecnicos"
        ],
        "summary": "Registra un nuevo tecnico en la base de datos",
        "description": "Se crea un tecnico nuevo y se retorna un json indicado si se guardó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "nombre": {
                  "type": "string",
                  "example": "Elias Colon"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha realizado correctamente y creado un nuevo tecnico.",
            "schema": {
              "$ref": "#/definitions/tecnicoCreado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      },
      "get": {
        "tags": [
          "Tecnicos"
        ],
        "summary": "Obtiene una lista de todos los tecnicos registrados en la base de datos",
        "description": "Este listado obtiene todo los tecnicos en la base de datos.",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "la solicitud se ha realizado correctamente.",
            "schema": {
              "$ref": "#/definitions/crearTecnico"
            }
          },
          "400": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          },
          "404": {
            "description": "Pentición no fue encontrada.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    },
    "/tecnicos/{id}": {
      "get": {
        "tags": [
          "Tecnicos"
        ],
        "summary": "Obtiene la información de un tecnico en particular a partir de su ID",
        "description": "Obtiene tecnico especifico según el ID en la base de datos.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "El ID del tecnico",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "la solicitud se ha realizado correctamente.",
            "schema": {
              "$ref": "#/definitions/crearTecnico"
            }
          },
          "400": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          },
          "404": {
            "description": "Pentición no fue encontrada.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      },
      "put": {
        "tags": [
          "Tecnicos"
        ],
        "summary": "Actualiza la información de un tecnico en particular a partir de su ID",
        "description": "Se actualiza un tecnico especifico y se retorna un json indicado si se actualizó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "El ID del tecnico",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "nombre": {
                  "type": "string",
                  "example": "Elias Colon"
                },
                "disponibilidad": {
                  "type": "string",
                  "example": true
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha actualizado correctamente el tecnico.",
            "schema": {
              "$ref": "#/definitions/tecnicoActualizado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    },
    "/solicitudes": {
      "post": {
        "tags": [
          "Solicitudes"
        ],
        "summary": "Crea una nueva solicitud de servicio",
        "description": "Se crea una nueva solicitud y se retorna un json indicado si se guardó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "id_cliente": {
                  "type": 12,
                  "example": 12
                },
                "descripcion": {
                  "type": "string",
                  "example": "Arreglar TV "
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha realizado correctamente y creado un nuevo servicio.",
            "schema": {
              "$ref": "#/definitions/servicioCreado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
       
      },
      "get": {
        "tags": [
          "Solicitudes"
        ],
        "summary": "Obtiene la información de todas las solicitudes de servicio",
        "description": "Este listado obtiene todo los servicios creados en la base de datos.",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "la solicitud se ha realizado correctamente.",
            "schema": {
              "$ref": "#/definitions/servicios"
            }
          },
          "400": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          },
          "404": {
            "description": "Pentición no fue encontrada.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    },
    "/tecnicos/{id}/solicitudes": {
      "get": {
        "tags": [
          "Solicitudes"
        ],
        "summary": "Obtiene la información de las solicitudes asignadas a un tecnico en particular a partir de su ID",
        "description": "Obtiene solicitudes especificas según el ID en la base de datos.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "El ID del tecnico",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Listado de servicios.",
            "schema": {
              "$ref": "#/definitions/serviciosTecnico"
            }
          },
          "400": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          },
          "404": {
            "description": "Pentición no fue encontrada.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    },
    "/solicitudes/{token}": {
      "put": {
        "tags": [
          "Solicitudes"
        ],
        "summary": "Actualiza el estado de un tecnico a solicitud en particular a partir de su token",
        "description": "Actualiza el estado de un tecnico especifico y se retorna un json indicado si se actualizó con exito o no.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "description": "El token de la solicitu",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "estado": {
                  "type": "string",
                  "example": "Completado"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Se ha actualizado correctamente el estado de la solicitud.",
            "schema": {
              "$ref": "#/definitions/servicioActualizado"
            }
          },
          "500": {
            "description": "El servidor no pudo entender la solicitud debido a una sintaxis incorrecta.",
            "schema": {
              "$ref": "#/definitions/errorRespuesta"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "crearCliente": {
      "required": [],
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "example": {
              "id": 2,
              "nombre": "Elias Colon",
              "direccion": "Carrera 8b",
              "correo": "eliascolon98@gmail.com",
              "telefono": 300882829,
              "createat": "2023-01-05T17:15:42.890Z"
            }
          }
        }
      }
    },
    "crearTecnico": {
      "required": [],
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "example": {
              "id": 1,
              "names": "Elias",
              "disponibilidad": true,
              "created_at": "2022-01-26T12:22:08.288Z"
            }
          }
        }
      }
    },
    "clienteCreado": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "¡El cliente se ha registrado exitosamente!"
        }
      }
    },
    "clienteActualizado": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "¡El cliente se ha actualizado exitosamente!"
        }
      }
    },
    "clienteEliminado": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "¡El cliente se ha eliminado exitosamente!"
        }
      }
    },
    "tecnicoCreado": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "¡El tecnico se ha registrado exitosamente!"
        }
      }
    },
    "tecnicoActualizado": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "¡El tecnico se ha actualizado exitosamente!"
        }
      }
    },
    "servicios": {
      "required": [
        "title",
        "description"
      ],
      "properties": {
        "services": {
          "type": "array",
          "items": {
            "type": "object",
            "example": {
              "id": 9,
              "token": "fa4edbd123e29671efe3cb957e7069a748ff3ecf",
              "descripcion": "arreglar estufa",
              "estado": "Completado",
              "cliente": "Elias Colon",
              "TecnicoAsigado": "Juancho"
            }
          }
        }
      }
    },
    "servicioCreado": {
      "required": [
        "id_cliente",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "Se ha registrado correctamente su número de ticket es 9"
        }
      }
    },
    "serviciosTecnico": {
      "required": [
        "title",
        "description"
      ],
      "properties": {
        "services": {
          "type": "array",
          "items": {
            "type": "object",
            "example": {
              "id": 9,
              "token": "fa4edbd123e29671efe3cb957e7069a748ff3ecf",
              "descripcion": "arreglar estufa",
              "estado": "Completado",
              "cliente": "Elias Colon"
            }
          }
        }
      }
    },
    "servicioActualizado": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "Estado actualizado exitosamente!"
        }
      }
    },
    "errorRespuesta": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "Error al procesar la petición al servidor + error especifico"
        }
      }
    }
  }
}